nodepool: apps

scanopy:
  server:
    image: ghcr.io/scanopy/scanopy/server:latest
    port: 60072
    publicUrl: http://10.2.1.101:60072

  daemon:
    image: ghcr.io/scanopy/scanopy/daemon:latest
    mode: Pull
    name: "scanopy-k8s"
    serverUrl: "http://scanopy.scanopy.svc.cluster.local:60072"
    networkId: "06c80a45-b3d1-4551-a565-9f073e7626d0"
    userId: "APPLICATION"

postgres:
  image: postgres:17
  db: scanopy
  user: postgres
  storage: 20Gi
