apiVersion: v1
kind: Service
metadata:
  name: imgproxy
  namespace: imgproxy
spec:
  type: LoadBalancer
  loadBalancerIP: 10.2.1.104
  selector:
    app: imgproxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
