apiVersion: v1
kind: ConfigMap
metadata:
  name: semaphore-config
  namespace: semaphore
data:
  SEMAPHORE_DB_DIALECT: sqlite
  SEMAPHORE_ADMIN: admin
  SEMAPHORE_ADMIN_NAME: Administrator
  SEMAPHORE_ADMIN_EMAIL: admin@local
  SEMAPHORE_ADMIN_PASSWORD: wMH3yCvtDZ#aT^r3SHx1
  SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore
