apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
  namespace: semaphore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semaphore
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      nodeSelector:
        nodepool: apps
      containers:
        - name: semaphore
          image: semaphoreui/semaphore:latest
          ports:
            - containerPort: 3000
          env:
            - name: SEMAPHORE_DB_DIALECT
              value: sqlite
            - name: SEMAPHORE_DB_HOST
              value: /home/semaphore/database.sqlite
            - name: SEMAPHORE_ADMIN
              value: admin
            - name: SEMAPHORE_ADMIN_PASSWORD
              value: changeme
            - name: SEMAPHORE_ADMIN_NAME
              value: Administrator
            - name: SEMAPHORE_ADMIN_EMAIL
              value: admin@local
            - name: SEMAPHORE_PLAYBOOK_PATH
              value: /tmp/semaphore
            - name: SEMAPHORE_PORT
              value: "3000"
            - name: SEMAPHORE_WEB_ROOT
              value: "/"
