apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgcompress
  namespace: imgcompress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imgcompress
  template:
    metadata:
      labels:
        app: imgcompress
    spec:
      containers:
        - name: imgcompress
          image: karimz1/imgcompress:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
