apiVersion: v1
kind: Service
metadata:
  name: imgcompress
  namespace: imgcompress
spec:
  type: LoadBalancer
  loadBalancerIP: 10.2.1.104
  selector:
    app: imgcompress
  ports:
    - name: http
      port: 80
      targetPort: 3000
